defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: node:13.12.0

version: 2.1
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install APT packages
          command: |
            apt-get update
            apt-get install -y jq zip nasm libgconf-2-4 wget --no-install-recommends
            wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
            apt-get install -y google-chrome-unstable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst ttf-freefont --no-install-recommends
      - restore_cache:
          keys:
            - v1-node-modules-{{ checksum "package-lock.json" }}
            - v1-node-modules-
      - run:
          name: Install Node modules
          command: npm install
      - save_cache:
          key: v1-node-modules-{{ checksum "package-lock.json" }}
          paths: [node_modules]
      - run:
          name: Build
          command: BUILD_NUMBER=$CIRCLE_SHA1 npm run build
      - run:
          name: Pack
          command: .circleci/pack.sh
      - store_artifacts:
          path: ~/repo/package
      - persist_to_workspace:
          root: .
          paths:
            - build/
            - node_modules/
  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: npm test
  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      # - deploy:
      #     name: Deploy to NPM
      #     command: .circleci/deploy_to_npm.sh
      # - deploy:
      #     name: Deploy to GitHub Pages
      #     command: .circleci/deploy_to_gh_pages.sh

workflows:
  version: 2.1
  build_test_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test:
          requires: [build]
          filters:
            tags:
              only: /.*/
      - deploy:
          context: npm_deployment
          requires: [test]
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
